#Lab 6: AI-Based Code Completion – Classes, Loops, and Conditionals
#===========================================

#Lab Objectives
# To explore AI-powered auto-completion features for core Python constructs such as classes,loops, and conditional statements.
# To analyze how AI tools suggest logic for object-oriented programming and control structures.
# To evaluate the correctness, readability, and completeness of AI-generated Python code.

#Lab Outcomes (LOs)
#After completing this lab, students will be able to:
# Use AI tools to generate and complete Python class definitions and methods.
# Understand and assess AI-suggested loop constructs for iterative tasks.
# Generate and evaluate conditional statements using AI-driven prompts.
# Critically analyze AI-assisted code for correctness, clarity, and efficiency.

#Task-1:- Classes(Student Class)
#===========================================

#I have to develop a simple student information management module.
#Write a python program to print the details of a student using a class named 'Student' with attributes like name, roll number, and branch.
#Add a method display_details() to print the student's information.
#Execute the code and verify the output.
#Analyze the code generated by the AI tool for correctness and clarity.

#Expected Output #1
# A Python class with a constructor (__init__) and a display_details() method.
# Sample object creation and output displayed on the console.
# Brief analysis of AI-generated code.

'''class Student:
    def __init__(self, name, roll_number, branch):
        self.name = name
        self.roll_number = roll_number
        self.branch = branch
    def display_details(self):
        print(f"Name: {self.name}")
        print(f"Roll Number: {self.roll_number}")
        print(f"Branch: {self.branch}")

# Creating an instance of the Student class and displaying details
if __name__ == "__main__":
    student = Student("John Doe", "12345", "Computer Science")
    student.display_details()'''

#Output Analysis:
# The AI-generated code correctly defines a Student class with the required attributes and methods.
# The constructor initializes the attributes, and the display_details() method prints them in a readable format.
# The code is clear, concise, and follows standard Python conventions for class definitions.
#Test Cases:
# Sample Input: Name: Alice, Roll Number: 67890, Branch: Mechanical Engineering
# Sample Output:
# Name: Alice
# Roll Number: 67890
# Branch: Mechanical Engineering

#Task-2:- Loops(Multiples of a Number)
#===========================================
#I have to write a utility function to display multiples of a given number.
#Write a python program to generate a function that prints the first 10 multiples of a given number using a loop.
#Analyze the generated loop logic.
#Ask the AI to generate the same functionality using another controlled looping structure (e.g.,
#I have to generate the same functionality using another controlled looping structure (e.g., while instead of for).

#Expected Output #2
#Correct loop-based Python implementation.
#Output showing the first 10 multiples of a number.
#Comparison and analysis of different looping approaches.
'''def print_multiples_for_loop(number):
    print(f"First 10 multiples of {number} using for loop:")
    for i in range(1, 11):
        print(number * i, end=" ")
    print()
def print_multiples_while_loop(number):
    print(f"First 10 multiples of {number} using while loop:")
    i = 1
    while i <= 10:
        print(number * i, end=" ")
        i += 1
    print()
# Example usage
if __name__ == "__main__":
    num = int(input("Enter a number: "))
    print_multiples_for_loop(num)
    print_multiples_while_loop(num)'''
#Output Analysis:
# The AI-generated code provides two functions to print the first 10 multiples of a given number.
# The first function uses a for loop, which is straightforward and efficient for this purpose.
# The second function uses a while loop, demonstrating an alternative approach to achieve the same result.
# Both implementations are correct and produce the expected output.
#Test Cases:
# Sample Input: 3
# Sample Output:
# First 10 multiples of 3 using for loop: 3 6 9 12 15 18 21 24 27 30
# First 10 multiples of 3 using while loop: 3 6 9 12 15 18 21 24 27 30

#Task-3:- Conditional Statements (Age Classification)
#===========================================
#I have to built a baasic classification system based on age.
#Write a python program to generate nested if-elif-else conditional statements to classify age groups(e.g., child, teenager, adult, senior).
#Analyze the generated conditions and logic.
#And generate the same classification using alternative conditional structures (e.g., simplified conditions or dictionary-based logic).

#Expected Output #3
#A Python function that classifies age into appropriate groups.
#Clear and correct conditional logic.
#Explanation of how the conditions work.
'''def classify_age_nested(age):
    if age < 0:
        return "Invalid age"
    elif age <= 12:
        return "Child"
    elif age <= 19:
        return "Teenager"
    elif age <= 59:
        return "Adult"
    else:
        return "Senior"
def classify_age_dict(age):
    if age < 0:
        return "Invalid age"
    age_groups = {
        range(0, 13): "Child",
        range(13, 20): "Teenager",
        range(20, 60): "Adult",
        range(60, 150): "Senior"
    }
    for age_range, group in age_groups.items():
        if age in age_range:
            return group
    return "Invalid age"
# Example usage
if __name__ == "__main__":
    age = int(input("Enter age: "))
    print(f"Age {age} classified using nested if-elif-else: {classify_age_nested(age)}")
    print(f"Age {age} classified using dictionary-based logic: {classify_age_dict(age)}")'''
#Output Analysis:
# The AI-generated code provides two functions to classify age groups.
# The first function uses nested if-elif-else statements, which clearly define the age ranges for each group.
# The second function uses a dictionary-based approach, which is more concise and easier to maintain.  
# Both implementations correctly classify ages into the defined groups.
#Test Cases:
# Sample Input: 10 --> Output: Child
# Sample Input: 16 --> Output: Teenager
# Sample Input: 30 --> Output: Adult
# Sample Input: 70 --> Output: Senior

#Task-4:- For and While Loops(Sum of First n Numbers)
#===========================================
#We have to calculate the sum of the first n natural numbers.
#Write a python program to generate a sum_to_n() function using a for loop.
#Analyze the generated code.
#Suggest an alternative implementation using a while loop or a mathimatical formula.

#Expected Output #4
#Python function to compute the sum of first n numbers.
#Correct output for sample inputs.
#Explanation and comparison of different approaches.
'''def sum_to_n_for_loop(n):
    total = 0
    for i in range(1, n + 1):
        total += i
    return total
def sum_to_n_while_loop(n):
    total = 0
    i = 1
    while i <= n:
        total += i
        i += 1
    return total
def sum_to_n_formula(n):
    return n * (n + 1) // 2
# Example usage
if __name__ == "__main__":
    n = int(input("Enter a natural number n: "))
    print(f"Sum of first {n} numbers using for loop: {sum_to_n_for_loop(n)}")
    print(f"Sum of first {n} numbers using while loop: {sum_to_n_while_loop(n)}")
    print(f"Sum of first {n} numbers using formula: {sum_to_n_formula(n)}")'''
#Output Analysis:
# The AI-generated code provides three functions to calculate the sum of the first n natural numbers.
# The first function uses a for loop, iterating through each number and accumulating the total.
# The second function uses a while loop, achieving the same result with a different looping structure.
# The third function uses the mathematical formula n(n+1)/2, which is the most efficient approach.
# All implementations produce the correct output for given inputs.
#Test Cases:
# Sample Input: 5 --> Output: 15
# Sample Input: 10 --> Output: 55
# Sample Input: 100 --> Output: 5050

#Task-5:- Classes(Bank Account Class)
#===========================================
#I want to design a basic banking application.
#Write a python program to generate a BankAccount class with methods such as deposit(), withdraw(), and check_balance().
#Analyze the AI-generated class structure and logic.
#Add meaningful comments and explain the working of the code.

#Expected Output #5
# Complete Python Bank Account class.
#Demonstration of deposit and withdrawal operations with updated balance.
#Well-commented code with a clear explanation.

class BankAccount:
    def __init__(self, account_holder, initial_balance=0):
        # Initialize the bank account with account holder's name and initial balance
        self.account_holder = account_holder
        self.balance = initial_balance

    def deposit(self, amount):
        # Deposit a specified amount into the account
        if amount > 0:
            self.balance += amount
            print(f"Deposited: ₹{amount:.2f}")
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        # Withdraw a specified amount from the account if sufficient balance exists
        if amount > 0:
            if amount <= self.balance:
                self.balance -= amount
                print(f"Withdrew: ₹{amount:.2f}")
            else:
                print("Insufficient balance for withdrawal.")
        else:
            print("Withdrawal amount must be positive.")

    def check_balance(self):
        # Check and return the current balance of the account
        return f"Current balance: ₹{self.balance:.2f}"
# Example usage
if __name__ == "__main__":
    account = BankAccount("Alice", 1000)
    print(account.check_balance())
    account.deposit(500)
    print(account.check_balance())
    account.withdraw(200)
    print(account.check_balance())
    account.withdraw(2000)  # Attempt to withdraw more than the balance
#Output Analysis:
# The AI-generated BankAccount class includes methods for depositing, withdrawing, and checking the balance.
# Each method includes basic validation to ensure that deposit and withdrawal amounts are positive and that sufficient funds are available for withdrawals.
# The code is well-structured and includes comments that explain the purpose of each method and key
# operations within them.
#Test Cases:
# Sample Input/Output:
# Initial Balance: ₹1000
# Deposit: ₹500 --> New Balance: ₹1500
# Withdraw: ₹200 --> New Balance: ₹1300
# Withdraw: ₹2000 --> Output: Insufficient balance for withdrawal.